### ISSUE TITLE
spelling and sphinx warning behavior differences

### ISSUE THREAD

**Issue by rscohn2** [sphinx-contrib/spelling#108]
sphinx and spelling behave differently in the way they handle warnings. The sphinx behavior works well with IDEs that have support for jumping to file and line in the source for the warning, which I use to correct issues.

With -q, sphinx still emits line-level warnings, but spelling only gives a summary:

```
rscohn2@rscohn1-MOBL:test$ rm -rf build && sphinx-build -M spelling source build -q
/home/rscohn2/local/Projects/doc/test/source/index.rst:11: WARNING: Unknown target name: "badlink".
WARNING: Found 1 misspelled words
rscohn2@rscohn1-MOBL:test$
```

If I want line level info, then I cannot use -q, but now I get a lot of other stuff that makes it hard to see the warnings. This is a tiny test project. My actual project has many more lines.

```
rscohn2@rscohn1-MOBL:test$ rm -rf build && sphinx-build -M spelling source build
Running Sphinx v3.2.1
Initializing Spelling Checker 7.0.0
making output directory... done
Ignoring wiki words
Ignoring acronyms
Ignoring Python builtins
Ignoring importable module names
Ignoring contributor names
Looking for custom word list in /home/rscohn2/local/Projects/doc/test/source/spelling_wordlist.txt
Scanning contributors
building [mo]: targets for 0 po files that are out of date
building [spelling]: all documents
updating environment: [new config] 1 added, 0 changed, 0 removed
reading sources... [100%] index

/home/rscohn2/local/Projects/doc/test/source/index.rst:11: WARNING: Unknown target name: "badlink".
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index
index.rst:9:Missspelled::Missspelled word
Writing /home/rscohn2/local/Projects/doc/test/build/spelling/index.spelling

WARNING: Found 1 misspelled words
build succeeded, 2 warnings.
rscohn2@rscohn1-MOBL:test$
```

Another issue is that sphinx gives full paths for files, but spelling only gives the path relative to the source directory. The IDE does not know how to find the file.

Ideally (for me), spelling would emit line level info even with sphinx -q and it would use full paths for files.

**Comment by dhellmann** [comment]
I think to fix this you would need to change the log call at https://github.com/sphinx-contrib/spelling/blob/master/sphinxcontrib/spelling/builder.py#L220 to be a warning instead of info message.

I believe the reason it was not like that in the first place was that with the `-W` option sphinx exits on the first warning, so you're only going to see one misspelled word at a time in the output. Maybe that means we should print some way other than logging, at least if `-W` is enabled. Or maybe the output should be managed differently so that all of the warnings are accumulated and output together using one call.

If you are interested in working on a patch to change the behavior, I would be happy to review the code and publish the release.

**Comment by rscohn2** [comment]
I will give it a try and add a config so you can choose old and new behavior

**Comment by dhellmann** [comment]
That sounds good. Thanks!
