### ISSUE TITLE
Exclude file(s) from spell checks

### ISSUE THREAD

**Issue by pawamoy** [sphinx-contrib/spelling#3]
Is there a way to exclude a file from the spelling check?

For instance I would like to exclude the CHANGELOG since it's auto-generated from my commit messages.

**Comment by ephracis** [comment]
Yes, I would like that as well. Or even better, have a directive so we can disable blocks inside files. Since we use Jinja to add automated data to the documentation, like a list of open Issues, it would be nice to be able to exclude that portion of the document.

I tried to use the `spelling` directive with a wildcard `*` but it didn't work. :(

**Comment by dhellmann** [comment]
Would a configuration option work for disabling the check for a limited number of files?

**Comment by ephracis** [comment]
Any progress on this one? A configuration option would be swell.

**Comment by dhellmann** [comment]
> Any progress on this one? A configuration option would be swell.

I don't know that I'm going to have time to work on this for the foreseeable future. I would be happy to help guide someone who wants to work on it themselves, though, and to review a PR.
