### ISSUE TITLE
Spell checks on translation files (.po)

### ISSUE THREAD

**Issue by humitos** [sphinx-contrib/spelling#42]
I found this extension super interesting. I ran it on my project and the output that it produces is really good. However, it does not seem to work with translations [following the standard flow that Sphinx provides](https://www.sphinx-doc.org/en/master/usage/advanced/intl.html)

Is it possible to run the spelling ckecks over the localized text picked from `.po` files instead of the original `.rst` files?

Edit: I'm using [`pospell`](https://pypi.org/project/pospell/) for this currently, but I wanted to integrate the spelling into the Sphinx process and use PyEnchant that looks more powerful.

**Comment by dhellmann** [comment]
I think to make the check use the translated file it would have to happen at a much later point in the build process. I think that happens during formatting, rather than when the source document is read, although I'm not 100% sure of that. The current implementation here uses the Builder interface, which happens much earlier in the process. 

If there is already a tool for spell checking translation files, maybe it would be better to focus on extending that tool's ability to use alternative dictionaries or filters or whatever features of enchant look useful?

**Comment by dhellmann** [comment]
I don't think this feature is something we'll incorporate into this tool.
